# fly.toml app configuration file generated for mycoins on 2024-10-20T06:42:24+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mytravelweather'
primary_region = 'ams'
kill_signal = "SIGINT"
kill_timeout = 5
processes = []


[env]
  FLET_SERVER_PORT = "8000"
  FLET_SESSION_TIMEOUT = "60"
  HOSTNAME = "0.0.0.0"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = "connections"
    soft_limit = 200
    hard_limit = 250


